export interface DistrictData {
  id: string;
  name: string;
  description: string;
  prisendring: string;
  prisendringDetail: string;
  salgstid: string;
  salgstidDetail: string;
  medianpris: string;
  medianprisDetail: string;
  perM2: string;
  perM2Detail: string;
}

export const osloAverage: DistrictData = {
  id: "oslo",
  name: "Oslo",
  description: "Er det kjøper eller selgers marked i Oslo nå?",
  prisendring: "+2.4 %",
  prisendringDetail: "Gjennomsnittlig prisendring siste 12 måneder i Oslo.",
  salgstid: "19 dager",
  salgstidDetail: "Gjennomsnittlig salgstid for boliger i Oslo.",
  medianpris: "5 800 000 kr",
  medianprisDetail: "Median salgspris for boliger i Oslo.",
  perM2: "95 000 kr",
  perM2Detail: "Gjennomsnittlig kvadratmeterpris i Oslo.",
};

export const districts: DistrictData[] = [
  {
    id: "gamle-oslo",
    name: "Gamle Oslo",
    description: "Historisk bydel med stor utvikling og et mangfoldig boligmarked.",
    prisendring: "+2.1 %",
    prisendringDetail: "-0.3 prosentpoeng under Oslo-snittet (2.4 %). Moderat prisvekst.",
    salgstid: "20 dager",
    salgstidDetail: "1 dag over Oslo-snittet (19 dager). Normal etterspørsel.",
    medianpris: "4 900 000 kr",
    medianprisDetail: "900 000 kr under Oslo-snittet (5 800 000). Lavere prisnivå.",
    perM2: "88 000 kr",
    perM2Detail: "7 000 kr/m² under Oslo-snittet (95 000 kr/m²). Rimeligere enn snittet.",
  },
  {
    id: "grunerløkka",
    name: "Grünerløkka",
    description: "Populær bydel med trendy atmosfære og høy etterspørsel.",
    prisendring: "+3.1 %",
    prisendringDetail: "+0.7 prosentpoeng over Oslo-snittet (2.4 %). Sterk prisvekst.",
    salgstid: "15 dager",
    salgstidDetail: "4 dager under Oslo-snittet (19 dager). Høy etterspørsel.",
    medianpris: "5 200 000 kr",
    medianprisDetail: "600 000 kr under Oslo-snittet (5 800 000). Nær snittet.",
    perM2: "98 000 kr",
    perM2Detail: "3 000 kr/m² over Oslo-snittet (95 000 kr/m²). Litt over snittet.",
  },
  {
    id: "sagene",
    name: "Sagene",
    description: "Attraktiv bydel med nærhet til Akerselva og variert boligmasse.",
    prisendring: "+2.7 %",
    prisendringDetail: "+0.3 prosentpoeng over Oslo-snittet (2.4 %). God prisvekst.",
    salgstid: "17 dager",
    salgstidDetail: "2 dager under Oslo-snittet (19 dager). God etterspørsel.",
    medianpris: "5 500 000 kr",
    medianprisDetail: "300 000 kr under Oslo-snittet (5 800 000). Nær snittet.",
    perM2: "96 000 kr",
    perM2Detail: "1 000 kr/m² over Oslo-snittet (95 000 kr/m²). På nivå med snittet.",
  },
  {
    id: "st-hanshaugen",
    name: "St. Hanshaugen",
    description: "Sentral beliggenhet med mange klassiske bygårder og parker.",
    prisendring: "+2.9 %",
    prisendringDetail: "+0.5 prosentpoeng over Oslo-snittet (2.4 %). Sterkere prisvekst enn byen for øvrig.",
    salgstid: "18 dager",
    salgstidDetail: "På nivå med Oslo-snittet (19 dager). Normal etterspørsel.",
    medianpris: "6 100 000 kr",
    medianprisDetail: "300 000 kr over Oslo-snittet (5 800 000). Høyere prisnivå.",
    perM2: "112 000 kr",
    perM2Detail: "17 000 kr/m² over Oslo-snittet (95 000 kr/m²). Høyere prisnivå enn byen for øvrig.",
  },
  {
    id: "frogner",
    name: "Frogner",
    description: "Eksklusivt vest-område med høy boligstandard og prestisjefylte adresser.",
    prisendring: "+1.8 %",
    prisendringDetail: "-0.6 prosentpoeng under Oslo-snittet (2.4 %). Moderat prisvekst.",
    salgstid: "22 dager",
    salgstidDetail: "3 dager over Oslo-snittet (19 dager). Noe lengre salgstid.",
    medianpris: "7 200 000 kr",
    medianprisDetail: "1 400 000 kr over Oslo-snittet (5 800 000). Høyt prisnivå.",
    perM2: "118 000 kr",
    perM2Detail: "23 000 kr/m² over Oslo-snittet (95 000 kr/m²). Blant byens dyreste.",
  },
  {
    id: "ullern",
    name: "Ullern",
    description: "Rolig og grønt vest-område med eneboliger og rekkehus.",
    prisendring: "+2.0 %",
    prisendringDetail: "-0.4 prosentpoeng under Oslo-snittet (2.4 %). Stabil prisvekst.",
    salgstid: "24 dager",
    salgstidDetail: "5 dager over Oslo-snittet (19 dager). Lengre salgstid.",
    medianpris: "8 500 000 kr",
    medianprisDetail: "2 700 000 kr over Oslo-snittet (5 800 000). Høyt prisnivå.",
    perM2: "95 000 kr",
    perM2Detail: "På nivå med Oslo-snittet (95 000 kr/m²).",
  },
  {
    id: "vestre-aker",
    name: "Vestre Aker",
    description: "Populært familieområde med nærhet til marka og gode skoler.",
    prisendring: "+1.9 %",
    prisendringDetail: "-0.5 prosentpoeng under Oslo-snittet (2.4 %). Moderat prisvekst.",
    salgstid: "21 dager",
    salgstidDetail: "2 dager over Oslo-snittet (19 dager). Normal salgstid.",
    medianpris: "9 200 000 kr",
    medianprisDetail: "3 400 000 kr over Oslo-snittet (5 800 000). Blant byens dyreste.",
    perM2: "88 000 kr",
    perM2Detail: "7 000 kr/m² under Oslo-snittet (95 000 kr/m²). Lavere kvm-pris pga. større boliger.",
  },
  {
    id: "nordre-aker",
    name: "Nordre Aker",
    description: "Attraktivt område med nærhet til Nordmarka og Universitetet.",
    prisendring: "+2.6 %",
    prisendringDetail: "+0.2 prosentpoeng over Oslo-snittet (2.4 %). God prisvekst.",
    salgstid: "18 dager",
    salgstidDetail: "1 dag under Oslo-snittet (19 dager). God etterspørsel.",
    medianpris: "7 000 000 kr",
    medianprisDetail: "1 200 000 kr over Oslo-snittet (5 800 000). Over snittet.",
    perM2: "89 000 kr",
    perM2Detail: "6 000 kr/m² under Oslo-snittet (95 000 kr/m²). Noe under snittet.",
  },
  {
    id: "bjerke",
    name: "Bjerke",
    description: "Variert bydel med god kollektivdekning og nye boligprosjekter.",
    prisendring: "+2.8 %",
    prisendringDetail: "+0.4 prosentpoeng over Oslo-snittet (2.4 %). Sterk prisvekst.",
    salgstid: "17 dager",
    salgstidDetail: "2 dager under Oslo-snittet (19 dager). God etterspørsel.",
    medianpris: "4 800 000 kr",
    medianprisDetail: "1 000 000 kr under Oslo-snittet (5 800 000). Rimeligere.",
    perM2: "78 000 kr",
    perM2Detail: "17 000 kr/m² under Oslo-snittet (95 000 kr/m²). Rimelig prisnivå.",
  },
  {
    id: "grorud",
    name: "Grorud",
    description: "Mangfoldig bydel med rimeligere boliger og god utvikling.",
    prisendring: "+3.2 %",
    prisendringDetail: "+0.8 prosentpoeng over Oslo-snittet (2.4 %). Sterkest prisvekst.",
    salgstid: "16 dager",
    salgstidDetail: "3 dager under Oslo-snittet (19 dager). Høy etterspørsel.",
    medianpris: "3 900 000 kr",
    medianprisDetail: "1 900 000 kr under Oslo-snittet (5 800 000). Rimelig prisnivå.",
    perM2: "65 000 kr",
    perM2Detail: "30 000 kr/m² under Oslo-snittet (95 000 kr/m²). Byens rimeligste.",
  },
  {
    id: "stovner",
    name: "Stovner",
    description: "Rimelig bydel med nærhet til natur og godt utbygd infrastruktur.",
    prisendring: "+3.5 %",
    prisendringDetail: "+1.1 prosentpoeng over Oslo-snittet (2.4 %). Sterkest prisvekst i Oslo.",
    salgstid: "14 dager",
    salgstidDetail: "5 dager under Oslo-snittet (19 dager). Svært høy etterspørsel.",
    medianpris: "3 600 000 kr",
    medianprisDetail: "2 200 000 kr under Oslo-snittet (5 800 000). Rimeligst i Oslo.",
    perM2: "58 000 kr",
    perM2Detail: "37 000 kr/m² under Oslo-snittet (95 000 kr/m²). Byens rimeligste.",
  },
  {
    id: "alna",
    name: "Alna",
    description: "Stor og mangfoldig bydel med ny utvikling langs T-banen.",
    prisendring: "+2.9 %",
    prisendringDetail: "+0.5 prosentpoeng over Oslo-snittet (2.4 %). God prisvekst.",
    salgstid: "16 dager",
    salgstidDetail: "3 dager under Oslo-snittet (19 dager). God etterspørsel.",
    medianpris: "4 100 000 kr",
    medianprisDetail: "1 700 000 kr under Oslo-snittet (5 800 000). Under snittet.",
    perM2: "68 000 kr",
    perM2Detail: "27 000 kr/m² under Oslo-snittet (95 000 kr/m²). Rimelig prisnivå.",
  },
  {
    id: "østensjø",
    name: "Østensjø",
    description: "Familievennlig bydel med god infrastruktur og nærhet til Østmarka.",
    prisendring: "+2.3 %",
    prisendringDetail: "-0.1 prosentpoeng under Oslo-snittet (2.4 %). På nivå med snittet.",
    salgstid: "19 dager",
    salgstidDetail: "På nivå med Oslo-snittet (19 dager). Normal etterspørsel.",
    medianpris: "5 000 000 kr",
    medianprisDetail: "800 000 kr under Oslo-snittet (5 800 000). Under snittet.",
    perM2: "76 000 kr",
    perM2Detail: "19 000 kr/m² under Oslo-snittet (95 000 kr/m²). Rimeligere enn snittet.",
  },
  {
    id: "nordstrand",
    name: "Nordstrand",
    description: "Rolig og etablert boligområde med sjøutsikt og gode skoler.",
    prisendring: "+2.0 %",
    prisendringDetail: "-0.4 prosentpoeng under Oslo-snittet (2.4 %). Moderat prisvekst.",
    salgstid: "21 dager",
    salgstidDetail: "2 dager over Oslo-snittet (19 dager). Normal salgstid.",
    medianpris: "6 500 000 kr",
    medianprisDetail: "700 000 kr over Oslo-snittet (5 800 000). Over snittet.",
    perM2: "82 000 kr",
    perM2Detail: "13 000 kr/m² under Oslo-snittet (95 000 kr/m²). Under snittet.",
  },
  {
    id: "søndre-nordstrand",
    name: "Søndre Nordstrand",
    description: "Rimelig bydel i sør med natur og mangfoldig befolkning.",
    prisendring: "+3.0 %",
    prisendringDetail: "+0.6 prosentpoeng over Oslo-snittet (2.4 %). Sterk prisvekst.",
    salgstid: "15 dager",
    salgstidDetail: "4 dager under Oslo-snittet (19 dager). Høy etterspørsel.",
    medianpris: "4 200 000 kr",
    medianprisDetail: "1 600 000 kr under Oslo-snittet (5 800 000). Under snittet.",
    perM2: "62 000 kr",
    perM2Detail: "33 000 kr/m² under Oslo-snittet (95 000 kr/m²). Blant byens rimeligste.",
  },
  {
    id: "sentrum",
    name: "Sentrum",
    description: "Byens hjerte med kontor, handel og et begrenset boligtilbud.",
    prisendring: "+1.5 %",
    prisendringDetail: "-0.9 prosentpoeng under Oslo-snittet (2.4 %). Svakere prisvekst.",
    salgstid: "25 dager",
    salgstidDetail: "6 dager over Oslo-snittet (19 dager). Lengre salgstid.",
    medianpris: "5 500 000 kr",
    medianprisDetail: "300 000 kr under Oslo-snittet (5 800 000). Nær snittet.",
    perM2: "105 000 kr",
    perM2Detail: "10 000 kr/m² over Oslo-snittet (95 000 kr/m²). Over snittet.",
  },
];